In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy
## create a 1d array

oneDarray=np.array([1,2,5,2,5,3,45])
print(oneDarray)
print(type(oneDarray),oneDarray.shape)

[ 1  2  5  2  5  3 45]
<class 'numpy.ndarray'> (7,)


In [44]:
## 2d array
oneDarray1=np.array([[[1,2,5,2],[1,4,5,5]]])
print(oneDarray1.shape)
oneDarray1.reshape(1,2,4)
oneDarray2=np.array([1,2,5,21,4,5,5])
print(oneDarray2.shape)
oneDarray2.reshape(1,7)## 1 row and 5 columns


(1, 2, 4)
(7,)


array([[ 1,  2,  5, 21,  4,  5,  5]])

In [51]:
oneDarray1=np.array([[[[[[[[[1,2,5,2],[1,4,5,5]]]]]]]]])
oneDarray1.shape
oneDarray1.reshape(1,1,2,4)


array([[[[1, 2, 5, 2],
         [1, 4, 5, 5]]]])

In [61]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
## identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,6])
arr2 = np.array([1,2,3,4,6])
print("addition:",arr1+arr2)
print("sub:",arr1-arr2)
print("mul:",arr1*arr2)
print("div:",arr1/arr2)

addition: [ 2  4  6  8 12]
sub: [0 0 0 0 0]
mul: [ 1  4  9 16 36]
div: [1. 1. 1. 1. 1.]


In [3]:
## univercial function

arr=np.array([2,3,4,5,6,7])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
[   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]


In [7]:
array1=np.array([[12,25,36],[45,7,18],[17,33,52]])
print(array1[2,2])

52


In [34]:
## array slicing and indexing
array21=np.array([[12,25,36],[45,7,18],[17,33,52],[17,33,52]])

print("array: \n",array21)



array: 
 [[12 25 36]
 [45  7 18]
 [17 33 52]
 [17 33 52]]


In [41]:
array21[1][0]
print(array21[1:,2:])
print(array21[1:,1:2])
print(array21[2:,2:3])

[[18]
 [52]
 [52]]
[[ 7]
 [33]
 [33]]
[[52]
 [52]]
